version: "3.8"

services:
  crypto-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    command:
      [
        "/bin/bash",
        "-c",
        "chmod +x /app/install-browsers.sh && /app/install-browsers.sh && /app/startup.sh",
      ]
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Exchange settings
      - ENABLE_BINANCE=true
      - ENABLE_OKX=true
      - ENABLE_COINBASE=true
      - ENABLE_KRAKEN=true
      - ENABLE_BYBIT=true
      - ENABLE_KUCOIN=true
      - ENABLE_GATEIO=true
      - ENABLE_MEXC=true

      # Announcement settings
      - ENABLE_BINANCE_ANNOUNCEMENTS=true
      - ENABLE_OKX_ANNOUNCEMENTS=true

      # Email settings (these are required)
      - EMAIL_ENABLED=true
      - EMAIL_SERVICE=sendgrid
      - EMAIL_FROM_NAME=Crypto Tracker
      - EMAIL_FROM_EMAIL=${EMAIL_FROM_EMAIL}
      - EMAIL_TO=${EMAIL_TO}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}

      # Check interval in minutes
      - CHECK_INTERVAL=15

      # Playwright browser paths - set both for maximum compatibility
      - PLAYWRIGHT_BROWSERS_PATH=/app/.playwright-browsers
      - PW_BROWSERS_PATH_CACHE=/root/.cache/ms-playwright

      # Display for Playwright
      - DISPLAY=:99
      - XVFB_WHD=1920x1080x24

      # Debug flags
      - DEBUG=pw:api,pw:browser
    volumes:
      - crypto_data:/app/data
      - playwright_browsers:/app/.playwright-browsers
      - playwright_cache:/root/.cache/ms-playwright
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "try { require('fs').statSync('/app/data/listings.json'); process.exit(0); } catch(e) { process.exit(1); }",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  crypto_data:
    driver: local
  playwright_browsers:
    driver: local
  playwright_cache:
    driver: local
